var bugs = [{"type":"tracker","aid":"10","cid":"101","pattern":"(pub\\.lookery\\.com\\/js\\/|lookery\\.com\\/look\\.js|\\/j\\/pub\\/look\\.js)","name":"Lookery","id":"1"},
{"type":"tracker","aid":"13","cid":"81","pattern":"google-analytics\\.com\\/(urchin\\.js|ga\\.js)","name":"Google Analytics","id":"2"},
{"type":"tracker","aid":"15","cid":"184","pattern":"\\.mybloglog\\.com\\/","name":"MyBlogLog","id":"3"},
{"type":"tracker","aid":"16","cid":"139","pattern":"(\\.quantserve\\.com\\/|\\/quant\\.js)","name":"Quantcast","id":"4"},
{"type":"tracker","aid":"1","cid":"183","pattern":"indextools\\.js","name":"IndexTools","id":"5"},
{"type":"tracker","aid":"17","cid":"153","pattern":"sitemeter\\.com\\/(js\\/counter\\.js|meter\\.asp)","name":"SiteMeter","id":"6"},
{"type":"ad","aid":"18","cid":"99","pattern":"www\\.lijit\\.com\\/informers\\/wijits","name":"Lijit","id":"7"},
{"type":"tracker","aid":"19","cid":"128","pattern":"(\\.1[12]2\\.2o7\\.net\\/|hitbox\\.com|\\.omtrdc\\.net\\/|\\/s(c)?_code[0-9a-zA-Z_-]*(\\.[0-9a-zA-Z_-]*)?\\.js|\\/(omniture|mbox|hbx|omniunih)(.*)?\\.js|common\\.onset\\.freedom\\.com\\/fi\\/analytics\\/cms\\/)","name":"Omniture","id":"8"},
{"type":"tracker","aid":"20","cid":"50","pattern":"cetrk\\.com\\/","name":"Crazy Egg","id":"9"},
{"type":"tracker","aid":"21","cid":"157","pattern":"(shots\\.snap\\.com\\/snap_shots\\.js|spa\\.snap\\.com\\/snap_preview_anywhere\\.js)","name":"Snap","id":"10"},
{"type":"tracker","aid":"22","cid":"162","pattern":"((www|secure)\\.statcounter\\.com\\/counter\\/(counter[0-9a-zA-Z_]*|frames)\\.js|c\\.statcounter\\.com\\/)","name":"Statcounter","id":"11"},
{"type":"tracker","aid":"44","cid":"299","pattern":"\\/piwik\\.js","name":"Piwik Analytics","id":"12"},
{"type":"tracker","aid":"23","cid":"150","pattern":"\\/mint\\/\\?js","name":"Mint","id":"13"},
{"type":"tracker","aid":"204","cid":"249","pattern":"facebook\\.com\\/beacon\\/","name":"Facebook Beacon","id":"14"},
{"type":"tracker","aid":"45","cid":"154","pattern":"www\\.typepad\\.com\\/t\\/stats","name":"Typepad Stats","id":"15"},
{"type":"tracker","aid":"24","cid":"21","pattern":"(stats\\.wordpress\\.com\\/|s\\.stats\\.wordpress\\.com\\/w\\.js)","name":"Wordpress Stats","id":"16"},
{"type":"tracker","aid":"26","cid":"86","pattern":"\\/salog\\.js\\.aspx","name":"HubSpot","id":"17"},
{"type":"tracker","aid":"27","cid":"183","pattern":"(\\.analytics\\.yahoo\\.com\\/indextools\\.js|ystat\\.js|\\.yimg\\.com\\/.*\\/ywa\\.js|\\.visualrevenue\\.com\\/vr\\.js)","name":"Yahoo Analytics","id":"18"},
{"type":"tracker","aid":"28","cid":"132","pattern":"otracking\\.com\\/js","name":"OrangeSoda","id":"19"},
{"type":"tracker","aid":"29","cid":"864","pattern":"analytics\\.engagd\\.com\\/archin-std\\.js","name":"Engagd","id":"20"},
{"type":"tracker","aid":"30","cid":"450","pattern":"\\.nuggad\\.net\\/bk","name":"Nugg.Ad","id":"21"},
{"type":"tracker","aid":"42","cid":"52","pattern":"static\\.crowdscience\\.com\\/start(-.*)?\\.js","name":"Crowd Science","id":"22"},
{"type":"ad","aid":"31","cid":"69","pattern":"(static\\.fmpub\\.net\\/(zone|site)\\/|dynamic\\.fmpub\\.net\\/adserver\\/|thirdparty\\.fmpub\\.net\\/placement\\/)","name":"Federated Media","id":"23"},
{"type":"ad","aid":"32","cid":"131","pattern":"((bid|d[0-9]?)\\.openx\\.(org|net)\\/|\\/(adg|adx)\\.js|\\/(afr|ajs|avw)\\.php)","name":"OpenX","id":"24"},
{"type":"ad","aid":"33","cid":"14","pattern":"(wms\\.assoc-amazon\\.com|rcm\\.amazon\\.com\\/e\\/cm|www\\.assoc-amazon\\.(com|ca|co\\.uk|de|jp)\\/(e\\/ir|s\\/(ads\\.js|asw\\.js|link-enhancer)))","name":"Amazon Associates","id":"25"},
{"type":"tracker","aid":"34","cid":"82","pattern":"(feeds\\.feedburner\\.com\\/~[fs]\\/|feedproxy\\.google\\.com\\/~fc\\/)","name":"FeedBurner","id":"26"},
{"type":"tracker","aid":"35","cid":"42","pattern":"clustrmaps\\.com\\/counter\\/","name":"ClustrMaps","id":"27"},
{"type":"tracker","aid":"36","cid":"70","pattern":"(feedjit\\.com\\/serve\\/|feedjit\\.com\\/map\\/)","name":"Feedjit","id":"28"},
{"type":"ad","aid":"37","cid":"80","pattern":"(\\.googlesyndication\\.com\\/pagead\\/|googletagservices\\.com\\/tag\\/js\\/gpt\\.js|partner\\.googleadservices\\.com\\/gampad\\/|feedads\\.g\\.doubleclick\\.net\\/~at)","name":"Google Adsense","id":"29"},
{"type":"tracker","aid":"38","cid":"47","pattern":"\\.hittail\\.com\\/mlt\\.js","name":"HitTail","id":"30"},
{"type":"tracker","aid":"39","cid":"74","pattern":"friendfeed\\.com\\/embed\\/widget\\/","name":"FriendFeed","id":"31"},
{"type":"tracker","aid":"40","cid":"87","pattern":"\\/woopra(\\.v(2|3|4))?\\.js","name":"Woopra","id":"32"},
{"type":"tracker","aid":"2","cid":"145","pattern":"static\\.scribefire\\.com\\/ads\\.js","name":"ScribeFire QuickAds","id":"33"},
{"type":"tracker","aid":"43","cid":"167","pattern":"\\.imrworldwide\\.com\\/","name":"NetRatings SiteCensus","id":"34"},
{"type":"ad","aid":"41","cid":"257","pattern":"(ad(-apac)?\\.([a-z][a-z]\\.)?doubleclick\\.net\\/|\\.doubleclick\\.net\\/pagead\\/)","name":"DoubleClick","id":"35"},
{"type":"ad","aid":"46","cid":"15","pattern":"(Tacoda_AMS_DDC_Header\\.js|an\\.tacoda\\.net\\/|an\\.secure\\.tacoda\\.net\\/)","name":"Tacoda","id":"36"},
{"type":"ad","aid":"47","cid":"1","pattern":"(ad\\.yieldmanager\\.com\\/|optimizedby\\.rmxads\\.com|e\\.yieldmanager\\.net\\/script\\.js)","name":"Right Media","id":"37"},
{"type":"tracker","aid":"48","cid":"114","pattern":"(content\\.dl-rms\\.com\\/|\\.dlqm\\.net\\/|\\.questionmarket\\.com\\/)","name":"Dynamic Logic","id":"38"},
{"type":"tracker","aid":"49","cid":"181","pattern":"(trackingTags_v1\\.1\\.js|\\/webtrends(.*)?\\.js|\\.webtrendslive\\.com)","name":"WebTrends","id":"39"},
{"type":"tracker","aid":"50","cid":"296","pattern":"(\\.xiti\\.com\\/(hit\\.xiti|get\\.at)|js_xiti\\.js|xtcore.js)","name":"XiTi","id":"40"},
{"type":"tracker","aid":"52","cid":"149","pattern":"(\\/share-this\\.php?akst_action|w\\.sharethis\\.com\\/)","name":"ShareThis","id":"41"},
{"type":"tracker","aid":"53","cid":"148","pattern":"(\\/seesmic_topposters_v2\\.js|seesmic-wp\\.js)","name":"Seesmic","id":"42"},
{"type":"tracker","aid":"54","cid":"4","pattern":"static\\.addtoany\\.com\\/menu\\/(feed|page)\\.js","name":"AddtoAny","id":"43"},
{"type":"tracker","aid":"55","cid":"38","pattern":"(\\/addthis_widget\\.(js|php)|\\.addthis\\.com\\/js\\/widget\\.(js|php)|l\\.addthiscdn\\.com)","name":"AddThis","id":"44"},
{"type":"ad","aid":"56","cid":"19","pattern":"(\\.revsci\\.net\\/|wunderloop\\.net\\/|ad\\.targetingmarketplace\\.com\\/|revsci\\.(.*)\\/gw\\.js)","name":"Revenue Science","id":"45"},
{"type":"tracker","aid":"57","cid":"76","pattern":"(ads|clients|container)\\.pointroll\\.com","name":"PointRoll","id":"46"},
{"type":"tracker","aid":"58","cid":"313","pattern":"\\/chartbeat\\.js","name":"ChartBeat","id":"47"},
{"type":"tracker","aid":"3","cid":"142","pattern":"(static\\.getclicky\\.com\\/|clicky\\.js)","name":"Clicky","id":"48"},
{"type":"tracker","aid":"59","cid":"177","pattern":"\\.uservoice\\.com\\/","name":"UserVoice","id":"49"},
{"type":"ad","aid":"60","cid":"168","pattern":"(pixel|optimized-by|tap-cdn)\\.rubiconproject\\.com\\/","name":"Rubicon","id":"50"},
{"type":"tracker","aid":"61","cid":"107","pattern":"www\\.conversionruler\\.com\\/bin\\/js\\.php","name":"ConversionRuler","id":"51"},
{"type":"tracker","aid":"62","cid":"143","pattern":"lct\\.salesforce\\.com\\/sfga\\.js","name":"Salesforce","id":"52"},
{"type":"tracker","aid":"63","cid":"15","pattern":"\\.(sphere|surphace)\\.com\\/widgets\\/sphereit\\/js","name":"Sphere","id":"53"},
{"type":"ad","aid":"64","cid":"51","pattern":"(widget\\.criteo\\.com|dis(.*)?\\.criteo\\.com)","name":"Criteo","id":"54"},
{"type":"ad","aid":"65","cid":"7","pattern":"(social\\.bidsystem\\.com\\/|cubics\\.com\\/displayAd\\.js)","name":"Cubics","id":"55"},
{"type":"tracker","aid":"66","cid":"88","pattern":"resources\\.infolinks\\.com\\/js\\/infolinks_main\\.js","name":"InfoLinks","id":"56"},
{"type":"tracker","aid":"5","cid":"144","pattern":"statisfy\\.net\\/javascripts\\/stats\\.js","name":"Statisfy","id":"57"},
{"type":"ad","aid":"67","cid":"112","pattern":"(ads(1)?\\.msn\\.com\\/library\\/dap\\.js|adsyndication\\.msn\\.com\\/delivery\\/getads\\.js)","name":"MSN Ads","id":"58"},
{"type":"tracker","aid":"68","cid":"134","pattern":"widgets\\.outbrain\\.com\\/","name":"Outbrain","id":"59"},
{"type":"tracker","aid":"69","cid":"82","pattern":"www\\.google\\.com\\/friendconnect\\/script\\/friendconnect\\.js","name":"Google FriendConnect","id":"60"},
{"type":"ad","aid":"183","cid":"159","pattern":"\\.specificclick\\.net\\/","name":"SpecificClick","id":"61"},
{"type":"ad","aid":"185","cid":"112","pattern":"(\\.atdmt\\.com\\/|\\.adbureau\\.net\\/)","name":"Microsoft Atlas","id":"62"},
{"type":"tracker","aid":"182","cid":"156","pattern":"assets\\.skribit\\.com\\/javascripts\\/SkribitSuggest\\.js","name":"Skribit","id":"63"},
{"type":"tracker","aid":"70","cid":"82","pattern":"www\\.google\\.com\\/coop\\/cse\\/brand","name":"Google Custom Search Engine","id":"64"},
{"type":"tracker","aid":"71","cid":"82","pattern":"www\\.google\\.com\\/uds\\/api?file","name":"Google AJAX Search API","id":"65"},
{"type":"ad","aid":"72","cid":"97","pattern":"kona\\.kontera\\.com\\/javascript\\/","name":"Kontera ContentLink","id":"66"},
{"type":"ad","aid":"73","cid":"3","pattern":"\\.adbrite\\.com\\/","name":"AdBrite","id":"67"},
{"type":"ad","aid":"74","cid":"9","pattern":"(\\.adultadworld\\.com\\/geopop\\/geoinject\\.js|\\.adultadworld\\.com\\/jsc\\/)","name":"AdultAdWorld","id":"68"},
{"type":"ad","aid":"75","cid":"85","pattern":"\\.gunggo\\.com\\/show_ad\\.ashx","name":"Gunggo","id":"69"},
{"type":"ad","aid":"76","cid":"57","pattern":"doublepimp\\.com\\/getad\\.js","name":"DoublePimp","id":"70"},
{"type":"tracker","aid":"77","cid":"136","pattern":"ads\\.sexinyourcity\\.com\\/","name":"SexInYourCity","id":"71"},
{"type":"tracker","aid":"78","cid":"40","pattern":"ads\\.(lzjl|clicksor)\\.com","name":"Clicksor","id":"72"},
{"type":"tracker","aid":"79","cid":"86","pattern":"static\\.hubspot\\.com\\/websiteGraderBadge\\/badge\\.js","name":"HubSpot WebsiteGrader","id":"73"},
{"type":"ad","aid":"80","cid":"16","pattern":"(js\\.adsonar\\.com\\/js\\/|ads\\.adsonar\\.com\\/adserving\\/)","name":"Quigo AdSonar","id":"74"},
{"type":"tracker","aid":"81","cid":"28","pattern":"www\\.blogcatalog\\.com\\/w\\/recent\\.php","name":"BlogCatalog","id":"75"},
{"type":"tracker","aid":"82","cid":"166","pattern":"\\.technorati\\.com\\/","name":"Technorati Widget","id":"76"},
{"type":"tracker","aid":"83","cid":"14","pattern":"xslt\\.alexa\\.com\\/site_stats\\/js\\/t\\/","name":"Alexa Traffic Rank","id":"77"},
{"type":"tracker","aid":"84","cid":"64","pattern":"(\\.tribalfusion\\.com\\/|tags\\.expo9\\.exponential\\.com\\/tags\\/)","name":"Tribal Fusion","id":"78"},
{"type":"tracker","aid":"85","cid":"311","pattern":"disqus\\.com\\/forums\\/","name":"Disqus","id":"79"},
{"type":"ad","aid":"86","cid":"155","pattern":"ads\\.sixapart\\.com\\/","name":"Six Apart Advertising","id":"80"},
{"type":"ad","aid":"87","cid":"29","pattern":"ads\\.blogherads\\.com\\/","name":"BlogHer Ads","id":"81"},
{"type":"ad","aid":"88","cid":"15","pattern":"(o\\.aolcdn\\.com\\/ads\\/adswrapper|o\\.aolcdn\\.com\\/js\\/mg2\\.js|(r1\\.ace|ace-tag|servedby|uac)\\.advertising\\.com|(at|pr|ar)\\.atwola\\.com\\/)","name":"Advertising.com","id":"82"},
{"type":"ad","aid":"89","cid":"15","pattern":"leadback\\.advertising\\.com\\/adcedge\\/lb","name":"LeadBack","id":"83"},
{"type":"tracker","aid":"199","cid":"54","pattern":"digg\\.com\\/[0-9a-zA-Z]*\\/diggthis\\.js","name":"DiggThis","id":"84"},
{"type":"ad","aid":"90","cid":"257","pattern":"\\.doubleclick\\.net\\/activity;","name":"DoubleClick Spotlight","id":"85"},
{"type":"tracker","aid":"91","cid":"295","pattern":"\\.overture\\.com\\/(partner\\/)?js","name":"Yahoo! Overture","id":"86"},
{"type":"tracker","aid":"92","cid":"20","pattern":"(www\\.)?intensedebate\\.com\\/js\\/","name":"Intense Debate","id":"87"},
{"type":"tracker","aid":"93","cid":"249","pattern":"(facebook\\.com\\/connect|connect\\.facebook\\.net|(static\\.ak\\.connect\\.facebook\\.com\\/.*\\.js\\.php|fbconnect\\.js))","name":"Facebook Connect","id":"88"},
{"type":"tracker","aid":"94","cid":"33","pattern":"(static\\.btbuckets\\.com\\/bt\\.js|\\.n\\.btbuckets\\.com\\/js)","name":"BTBuckets","id":"89"},
{"type":"ad","aid":"95","cid":"84","pattern":"(cdn|g2|gonzogrape)\\.gumgum\\.com\\/javascripts\\/ggv2\\.js","name":"gumgum","id":"90"},
{"type":"ad","aid":"96","cid":"186","pattern":"hook\\.yieldbuild\\.com\\/s_ad\\.js","name":"YieldBuild","id":"91"},
{"type":"tracker","aid":"97","cid":"253","pattern":"d\\.yimg\\.com\\/ds\\/badge\\.js","name":"Yahoo! Buzz","id":"92"},
{"type":"tracker","aid":"98","cid":"24","pattern":"(baynote\\.net|baynote(-observer)?([0-9]+)?\\.js)","name":"Baynote Observer","id":"93"},
{"type":"ad","aid":"99","cid":"170","pattern":"triggit\\.com\\/tool\\/javascripts\\/trg_bs\\.js","name":"TriggIt","id":"94"},
{"type":"tracker","aid":"100","cid":"55","pattern":"digg\\.com\\/tools\\/widgetjs","name":"Digg Widget","id":"95"},
{"type":"tracker","aid":"101","cid":"138","pattern":"cache\\.blogads\\.com\\/","name":"Blogads","id":"96"},
{"type":"ad","aid":"102","cid":"188","pattern":"\\.zedo\\.com\\/","name":"Zedo","id":"97"},
{"type":"ad","aid":"103","cid":"179","pattern":"\\.intellitxt\\.com","name":"Vibrant Ads","id":"98"},
{"type":"tracker","aid":"104","cid":"77","pattern":"s3\\.amazonaws\\.com\\/getsatisfaction\\.com\\/(feedback\\/feedback\\.js|javascripts\\/feedback-v2\\.js)","name":"GetSatisfaction","id":"99"},
{"type":"ad","aid":"105","cid":"6","pattern":"(ad\\.afy11\\.net\\/(srad|srwidget)\\.js|beacon\\.afy11\\.net\\/)","name":"Adify","id":"100"},
{"type":"tracker","aid":"6","cid":"82","pattern":"gmodules.com\\/","name":"Google Widgets","id":"101"},
{"type":"tracker","aid":"106","cid":"100","pattern":"server\\.iad\\.liveperson\\.net\\/","name":"LivePerson","id":"102"},
{"type":"tracker","aid":"107","cid":"94","pattern":"\\/k_(push|button)\\.js","name":"Kampyle","id":"103"},
{"type":"tracker","aid":"108","cid":"41","pattern":"\\.clicktale\\.net\\/","name":"ClickTale","id":"104"},
{"type":"ad","aid":"109","cid":"103","pattern":"\\.crwdcntrl\\.net\\/","name":"Lotame","id":"105"},
{"type":"ad","aid":"110","cid":"49","pattern":"adserving\\.cpxinteractive\\.com\\/","name":"CPX Interactive","id":"106"},
{"type":"tracker","aid":"111","cid":"104","pattern":"lypn\\.com\\/lp\\/","name":"Lynchpin Analytics","id":"107"},
{"type":"tracker","aid":"112","cid":"171","pattern":"revelations\\.trovus\\.co\\.uk\\/tracker\\/","name":"Trovus Revelations","id":"108"},
{"type":"tracker","aid":"113","cid":"128","pattern":"touchclarity","name":"Omniture TouchClarity","id":"109"},
{"type":"tracker","aid":"114","cid":"90","pattern":"\\.insightexpressai\\.com\\/","name":"InsightExpress","id":"110"},
{"type":"ad","aid":"115","cid":"95","pattern":"\\.kanoodle\\.com\\/","name":"Kanoodle","id":"111"},
{"type":"tracker","aid":"116","cid":"31","pattern":"(tags\\.bluekai\\.com\\/|bkrtx\\.com\\/js\\/)","name":"BlueKai","id":"112"},
{"type":"tracker","aid":"117","cid":"102","pattern":"(tr-metrics\\.loomia\\.com|assets\\.loomia\\.com\\/js\\/)","name":"Loomia","id":"113"},
{"type":"tracker","aid":"118","cid":"168","pattern":"othersonline\\.com\\/*\\/[a-z0-9]+\\.js","name":"Others Online","id":"114"},
{"type":"tracker","aid":"119","cid":"175","pattern":"twittercounter\\.com\\/remote\\/","name":"TwitterCounter","id":"115"},
{"type":"tracker","aid":"7","cid":"146","pattern":"rate\\.thummit\\.com\\/js\\/","name":"Thummit","id":"116"},
{"type":"tracker","aid":"120","cid":"56","pattern":"(\\.dtmpub\\.com\\/|login\\.dotomi\\.com\\/ucm\\/ucmcontroller)","name":"Dotomi","id":"117"},
{"type":"ad","aid":"121","cid":"37","pattern":"scripts\\.chitika\\.net\\/","name":"Chitika","id":"118"},
{"type":"ad","aid":"122","cid":"160","pattern":"ad\\.spot200\\.com\\/","name":"Spot200","id":"119"},
{"type":"tracker","aid":"123","cid":"120","pattern":"counter\\.hitslink\\.com\\/(track\\.js|statistics\\.asp)","name":"HitsLink","id":"120"},
{"type":"tracker","aid":"124","cid":"22","pattern":"www\\.w3counter\\.com\\/tracker\\.js","name":"W3Counter","id":"121"},
{"type":"tracker","aid":"125","cid":"23","pattern":"awstats_misc_tracker\\.js","name":"AWStats","id":"122"},
{"type":"tracker","aid":"126","cid":"130","pattern":"stat\\.onestat\\.com\\/","name":"OneStat","id":"123"},
{"type":"tracker","aid":"8","cid":"174","pattern":"twitter\\.com\\/(javascripts\\/[0-9a-z]+\\.js|statuses\\/user_timeline\\/)","name":"Twitter Badge","id":"124"},
{"type":"tracker","aid":"128","cid":"32","pattern":"\\.bmmetrix\\.com\\/","name":"Bluemetrix","id":"126"},
{"type":"tracker","aid":"129","cid":"110","pattern":"include\\.reinvigorate\\.net\\/","name":"Reinvigorate","id":"127"},
{"type":"tracker","aid":"130","cid":"10","pattern":"api\\.postrank\\.com\\/","name":"PostRank","id":"128"},
{"type":"tracker","aid":"131","cid":"43","pattern":"service\\.collarity\\.com\\/","name":"Collarity","id":"129"},
{"type":"tracker","aid":"132","cid":"2","pattern":"\\.smrtlnks\\.com\\/","name":"AdaptiveBlue SmartLinks","id":"130"},
{"type":"tracker","aid":"133","cid":"172","pattern":"www\\.tumblr\\.com\\/dashboard\\/iframe","name":"Tumblr","id":"131"},
{"type":"tracker","aid":"134","cid":"73","pattern":"blogrollr\\.com\\/embed\\.js","name":"BlogRollr","id":"132"},
{"type":"ad","aid":"135","cid":"36","pattern":"\\.casalemedia\\.com\\/","name":"Casale Media","id":"133"},
{"type":"tracker","aid":"136","cid":"5","pattern":"track\\.blogcounter\\.de\\/","name":"BlogCounter","id":"134"},
{"type":"tracker","aid":"137","cid":"116","pattern":"api\\.widgetbucks\\.com\\/script\\/ads\\.js","name":"WidgetBucks","id":"135"},
{"type":"tracker","aid":"138","cid":"125","pattern":"www\\.nooked\\.com\\/javascripts\\/clearspring\\.js","name":"Nooked","id":"136"},
{"type":"tracker","aid":"139","cid":"178","pattern":"(\\.mediaplex\\.com|\\.fastclick\\.net)\\/","name":"ValueClick Mediaplex","id":"137"},
{"type":"tracker","aid":"140","cid":"93","pattern":"(www\\.haloscan\\.com\\/load\\/|js-kit\\.com\\/[0-9a-z\\/]+\\.js)","name":"JS-Kit","id":"138"},
{"type":"tracker","aid":"141","cid":"706","pattern":"buzzster\\.com\\/widget\\/","name":"Buzzster","id":"139"},
{"type":"tracker","aid":"142","cid":"98","pattern":"\\/trackalyze\\.js","name":"LeadLander","id":"140"},
{"type":"ad","aid":"143","cid":"34","pattern":"(\\.burstbeacon\\.com\\/|\\.burstnet\\.com\\/)","name":"Burst Media","id":"141"},
{"type":"tracker","aid":"144","cid":"187","pattern":"\\.metricsdirect\\.com\\/","name":"Zango","id":"142"},
{"type":"tracker","aid":"145","cid":"8","pattern":"(bspixel\\.bidsystem\\.com\\/|bidsystem\\.adknowledge\\.com\\/)","name":"Adknowledge","id":"143"},
{"type":"tracker","aid":"146","cid":"118","pattern":"\\.nebuadserving\\.com\\/","name":"NebuAd","id":"144"},
{"type":"ad","aid":"147","cid":"111","pattern":"\\.media6degrees\\.com\\/","name":"Media6Degrees","id":"145"},
{"type":"tracker","aid":"148","cid":"75","pattern":"\\/functionalTrends\\.js","name":"FunctionalTrends","id":"146"},
{"type":"tracker","aid":"149","cid":"126","pattern":"\\.nuconomy\\.com\\/n\\.js","name":"Nuconomy","id":"147"},
{"type":"tracker","aid":"150","cid":"253","pattern":"(\\.adrevolver\\.com|ads\\.bluelithium\\.com)\\/","name":"Bluelithium","id":"148"},
{"type":"ad","aid":"151","cid":"78","pattern":"\\.glam\\.com\\/app\\/site\\/affiliate\\/viewChannelModule\\.act","name":"Glam Media","id":"149"},
{"type":"tracker","aid":"152","cid":"121","pattern":"storage\\.trafic\\.ro\\/js\\/trafic\\.js","name":"Trafic","id":"150"},
{"type":"tracker","aid":"153","cid":"105","pattern":"\\.clicktracks\\.com\\/","name":"Lyris ClickTracks","id":"151"},
{"type":"tracker","aid":"154","cid":"61","pattern":"\\.enquisite\\.com\\/log\\.js","name":"Enquisite","id":"152"},
{"type":"tracker","aid":"155","cid":"65","pattern":"\\.extreme-dm\\.com\\/","name":"eXTReMe Tracker","id":"153"},
{"type":"tracker","aid":"9","cid":"112","pattern":"analytics\\.live\\.com\\/","name":"Microsoft Analytics","id":"154"},
{"type":"tracker","aid":"156","cid":"165","pattern":"\\.sweepery\\.com\\/javascripts\\/*\\/[0-9a-zA-Z_]*\\.js","name":"Sweepery","id":"155"},
{"type":"tracker","aid":"201","cid":"137","pattern":"(cdn|taf)\\.socialtwist\\.com[:80]*\\/*\\/(script|shoppr\\.core)\\.js","name":"Tell-a-Friend","id":"156"},
{"type":"tracker","aid":"207","cid":"169","pattern":"(tracking\\.percentmobile\\.com\\/|\\/percent_mobile\\.js)","name":"PercentMobile","id":"157"},
{"type":"tracker","aid":"158","cid":"122","pattern":"stat\\.netmonitor\\.fi\\/js\\/","name":"NetMonitor","id":"158"},
{"type":"tracker","aid":"159","cid":"108","pattern":"munchkin\\.marketo\\.net\\/","name":"Marketo","id":"159"},
{"type":"tracker","aid":"160","cid":"53","pattern":"(api|leads)\\.demandbase\\.com\\/","name":"Demandbase","id":"160"},
{"type":"ad","aid":"161","cid":"72","pattern":"pixel\\.fetchback\\.com\\/","name":"Fetchback","id":"161"},
{"type":"tracker","aid":"162","cid":"152","pattern":"gw-services\\.vtrenz\\.net\\/","name":"Silverpop","id":"162"},
{"type":"tracker","aid":"163","cid":"48","pattern":"(\\/eluminate\\.js|data\\.cmcore\\.com\\/imp)","name":"Coremetrics","id":"163"},
{"type":"tracker","aid":"164","cid":"106","pattern":"www\\.dialogmgr\\.com\\/tag\\/lib\\.js","name":"Magnify360","id":"164"},
{"type":"tracker","aid":"165","cid":"68","pattern":"tracking\\.fathomseo\\.com\\/","name":"Fathom SEO","id":"165"},
{"type":"tracker","aid":"166","cid":"60","pattern":"(now\\.eloqua\\.com|elqcfg[xml]*\\.js|elqimg\\.js)","name":"Eloqua","id":"166"},
{"type":"tracker","aid":"167","cid":"11","pattern":"\\.imiclk\\.com\\/","name":"Acerno","id":"167"},
{"type":"ad","aid":"168","cid":"115","pattern":"\\.mmismm\\.com\\/","name":"Mindset Media","id":"168"},
{"type":"tracker","aid":"169","cid":"79","pattern":"rt\\.trafficfacts\\.com\\/","name":"GoDaddy Site Analytics","id":"169"},
{"type":"ad","aid":"170","cid":"17","pattern":"\\.adnxs\\.com\\/","name":"AdNexus","id":"170"},
{"type":"ad","aid":"171","cid":"12","pattern":"\\.pro-market\\.net\\/","name":"AlmondNet","id":"171"},
{"type":"ad","aid":"200","cid":"44","pattern":"\\.collective-media\\.net\\/","name":"Collective Media","id":"172"},
{"type":"tracker","aid":"172","cid":"63","pattern":"\\.exelator\\.com\\/","name":"eXelate","id":"173"},
{"type":"ad","aid":"173","cid":"123","pattern":"\\.fimserve\\.com\\/","name":"Fox Audience Network","id":"174"},
{"type":"ad","aid":"174","cid":"91","pattern":"\\.interclick\\.com\\/","name":"interclick","id":"175"},
{"type":"tracker","aid":"175","cid":"124","pattern":"\\.nexac\\.com\\/","name":"NextAction","id":"176"},
{"type":"tracker","aid":"176","cid":"46","pattern":"\\.trafficmp\\.com\\/","name":"Traffic Marketplace","id":"177"},
{"type":"ad","aid":"177","cid":"173","pattern":"\\.turn\\.com\\/","name":"Turn","id":"178"},
{"type":"tracker","aid":"178","cid":"259","pattern":"(\\.realmedia\\.com\\/|realmedia\\/ads\\/|\\.247realmedia\\.com\\/realmedia\\/ads\\/)","name":"24/7 Real Media","id":"179"},
{"type":"tracker","aid":"186","cid":"62","pattern":"code\\.etracker\\.com\\/","name":"etracker","id":"180"},
{"type":"tracker","aid":"187","cid":"45","pattern":"\\.(scoreresearch|securestudies|scorecardresearch)\\.com\\/","name":"Comscore Beacon","id":"181"},
{"type":"tracker","aid":"179","cid":"27","pattern":"(\\.bizographics\\.com\\/|ad\\.bizo\\.com\\/pixel)","name":"Bizo","id":"182"},
{"type":"tracker","aid":"191","cid":"158","pattern":"\\.snoobi\\.com\\/snoop\\.php","name":"Snoobi","id":"183"},
{"type":"tracker","aid":"192","cid":"141","pattern":"\\.rfihub\\.com\\/","name":"Rocket Fuel","id":"184"},
{"type":"tracker","aid":"194","cid":"151","pattern":"(codice|codicebusiness)\\.shinystat\\.(com|it)\\/","name":"ShinyStat","id":"185"},
{"type":"tracker","aid":"195","cid":"180","pattern":"(sniff|stats)\\.visistat\\.com\\/","name":"VisiStat","id":"186"},
{"type":"tracker","aid":"196","cid":"119","pattern":"\\.sitestat\\.com\\/","name":"NedStat","id":"187"},
{"type":"tracker","aid":"197","cid":"176","pattern":"(\\.tynt\\.com\\/ti\\.js|\\.tynt\\.com\\/javascripts\\/tracer\\.js)","name":"Tynt Insight","id":"188"},
{"type":"tracker","aid":"198","cid":"71","pattern":"\\.i-stats\\.com\\/js\\/icounter\\.js","name":"i-stats","id":"189"},
{"type":"tracker","aid":"203","cid":"164","pattern":"tracking\\.summitmedia\\.co\\.uk\\/js\\/","name":"Summit Media","id":"190"},
{"type":"tracker","aid":"208","cid":"185","pattern":"\\.yandex\\.ru\\/(resource|metrika)\\/watch\\.js","name":"Yandex.Metrics","id":"191"},
{"type":"tracker","aid":"209","cid":"294","pattern":"ad\\.adriver\\.ru\\/","name":"AdRiver","id":"192"},
{"type":"tracker","aid":"210","cid":"161","pattern":"\\.spylog\\.(com|ru)\\/","name":"Openstat","id":"193"},
{"type":"tracker","aid":"214","cid":"39","pattern":"\\.conversiondashboard\\.com\\/","name":"ClickFuel","id":"194"},
{"type":"tracker","aid":"242","cid":"229","pattern":"(spruce\\.rapleaf\\.com|\\.rlcdn\\.com)","name":"RapLeaf","id":"195"},
{"type":"tracker","aid":"213","cid":"189","pattern":"static\\.zemanta\\.com\\/","name":"Zemanta","id":"196"},
{"type":"tracker","aid":"212","cid":"13","pattern":"(atrk|certify)\\.alexametrics\\.com\\/","name":"Alexa Metrics","id":"197"},
{"type":"tracker","aid":"215","cid":"96","pattern":"vizisense\\.komli\\.net\\/pixel\\.js","name":"ViziSense","id":"198"},
{"type":"tracker","aid":"211","cid":"299","pattern":"\\/phpmyvisites\\.js","name":"phpMyVisites","id":"199"},
{"type":"tracker","aid":"217","cid":"58","pattern":"cdn\\.doubleverify\\.com\\/[0-9a-zA-Z_-]*\\.js","name":"DoubleVerify","id":"200"},
{"type":"tracker","aid":"218","cid":"163","pattern":"one\\.statsit\\.com\\/","name":"Statsit","id":"201"},
{"type":"tracker","aid":"219","cid":"135","pattern":"\\.leadforce1\\.com\\/bf\\/bf\\.js","name":"LeadForce1","id":"202"},
{"type":"tracker","aid":"228","cid":"215","pattern":"widgets\\.backtype\\.com\\/","name":"BackType Widgets","id":"203"},
{"type":"tracker","aid":"220","cid":"92","pattern":"(ipinvite|group11|4qinvite\\.4q)\\.iperceptions\\.com\\/","name":"iPerceptions","id":"204"},
{"type":"tracker","aid":"221","cid":"147","pattern":"\\.searchforce\\.net\\/","name":"SearchForce","id":"205"},
{"type":"tracker","aid":"244","cid":"231","pattern":"tweetboard\\.com\\/tb\\.js","name":"Tweetboard","id":"206"},
{"type":"tracker","aid":"245","cid":"232","pattern":"(tweetmeme\\.com\\/i\\/scripts\\/button\\.js|zulu\\.tweetmeme\\.com\\/button_ajax\\.js)","name":"TweetMeme","id":"207"},
{"type":"tracker","aid":"222","cid":"190","pattern":"\\.zendesk\\.com\\/external\\/zenbox\\/overlay\\.js","name":"Zendesk","id":"208"},
{"type":"tracker","aid":"223","cid":"89","pattern":"\\.ivwbox\\.de\\/","name":"INFOnline","id":"209"},
{"type":"ad","aid":"224","cid":"140","pattern":"(media|recs).richrelevance\\.com\\/","name":"RichRelevance","id":"210"},
{"type":"tracker","aid":"237","cid":"224","pattern":"counter\\.yadro\\.ru\\/","name":"LiveInternet","id":"211"},
{"type":"tracker","aid":"247","cid":"234","pattern":"vistrac\\.com\\/static\\/vt\\.js","name":"vistrac","id":"212"},
{"type":"tracker","aid":"229","cid":"216","pattern":"\\.blvdstatus\\.com\\/js\\/initBlvdJS\\.php","name":"BLVD Status","id":"213"},
{"type":"tracker","aid":"232","cid":"219","pattern":"clixpy\\.com\\/clixpy\\.js","name":"Clixpy","id":"214"},
{"type":"tracker","aid":"238","cid":"225","pattern":"logdy\\.com\\/scripts\\/script\\.js","name":"Logdy","id":"215"},
{"type":"tracker","aid":"248","cid":"235","pattern":"widgetserver\\.com\\/syndication\\/subscriber","name":"WidgetBox","id":"216"},
{"type":"tracker","aid":"230","cid":"217","pattern":"widgets\\.clearspring\\.com\\/","name":"ClearSpring","id":"217"},
{"type":"tracker","aid":"225","cid":"81","pattern":"\\.google-analytics\\.com\\/siteopt\\.js","name":"Google Website Optimizer","id":"218"},
{"type":"tracker","aid":"226","cid":"117","pattern":"lt\\.navegg\\.com\\/lt\\.js","name":"Navegg","id":"219"},
{"type":"tracker","aid":"234","cid":"221","pattern":"\\.rsvpgenius\\.com\\/","name":"Genius","id":"220"},
{"type":"tracker","aid":"249","cid":"236","pattern":"tracker\\.wordstream\\.com\\/","name":"WordStream","id":"221"},
{"type":"tracker","aid":"235","cid":"222","pattern":"\\.kissmetrics\\.com\\/","name":"KissMetrics","id":"222"},
{"type":"tracker","aid":"240","cid":"227","pattern":"api\\.mixpanel\\.com\\/","name":"MixPanel","id":"223"},
{"type":"ad","aid":"227","cid":"214","pattern":"\\.adtegrity\\.net\\/","name":"Adtegrity","id":"224"},
{"type":"tracker","aid":"246","cid":"233","pattern":"(\\.unica\\.com\\/|ntpagetag)","name":"Unica","id":"225"},
{"type":"tracker","aid":"233","cid":"220","pattern":"rover\\.ebay\\.com\\/","name":"eBay Stats","id":"226"},
{"type":"tracker","aid":"243","cid":"230","pattern":"\\.inq\\.com\\/","name":"TouchCommerce","id":"227"},
{"type":"tracker","aid":"231","cid":"218","pattern":"\\.clixmetrix\\.com\\/","name":"ClixMetrix","id":"228"},
{"type":"tracker","aid":"236","cid":"223","pattern":"\\/liveball_api\\.js","name":"LiveBall","id":"229"},
{"type":"tracker","aid":"239","cid":"226","pattern":"\\.marinsm\\.com\\/","name":"Marin Search Marketer","id":"230"},
{"type":"tracker","aid":"241","cid":"228","pattern":"(cid|pi)\\.pardot\\.com\\/","name":"Pardot","id":"231"},
{"type":"tracker","aid":"250","cid":"237","pattern":"js\\.stormiq\\.com/sid[0-9]*_[0-9]*\\.[0-9]*\\.js","name":"DC StormIQ","id":"447"},
{"type":"tracker","aid":"251","cid":"238","pattern":"(\\.histats\\.com\\/js[0-9][0-9]?(.*)?\\.js|s[1-9][1-9]?\\.histats\\.com\\/stats\\/)","name":"Histats","id":"448"},
{"type":"tracker","aid":"252","cid":"239","pattern":"(widgets\\.amung\\.us\\/.*\\.js|whos\\.amung\\.us\\/widget\\/)","name":"Whos.amung.us","id":"449"},
{"type":"tracker","aid":"253","cid":"240","pattern":"\\.gosquared\\.com\\/livestats\\/tracker","name":"GoSquared LiveStats","id":"450"},
{"type":"tracker","aid":"254","cid":"241","pattern":"www\\.apture\\.com\\/js\\/apture\\.js","name":"Apture","id":"451"},
{"type":"tracker","aid":"255","cid":"243","pattern":"c\\.compete\\.com\\/bootstrap\\/.*\\/bootstrap\\.js","name":"CompeteXL","id":"453"},
{"type":"tracker","aid":"257","cid":"276","pattern":"(s3\\.amazonaws\\.com\\/wingify\\/vis_opt\\.js|dev\\.visualwebsiteoptimizer\\.com\\/deploy\\/js_visitor_settings\\.php.*|server\\.wingify\\.com\\/app\\/js\\/code\\/wg_consolidated\\.js)","name":"Visual Website Optimizer","id":"455"},
{"type":"tracker","aid":"258","cid":"277","pattern":"mashlogic\\.com\\/(loader\\.min\\.js|brands\\/embed\\/)","name":"MashLogic","id":"457"},
{"type":"tracker","aid":"259","cid":"278","pattern":"s3\\.buysellads\\.com","name":"BuySellAds","id":"458"},
{"type":"tracker","aid":"260","cid":"315","pattern":"cim\\.meebo\\.com\\/cim","name":"Meebo Bar","id":"459"},
{"type":"tracker","aid":"261","cid":"316","pattern":"(c1|beta)\\.web-visor\\.com\\/c\\.js","name":"WebVisor","id":"460"},
{"type":"tracker","aid":"262","cid":"317","pattern":"stags\\.peer39\\.net\\/","name":"Peer39","id":"461"},
{"type":"tracker","aid":"263","cid":"327","pattern":"\\.eproof\\.com\\/js\\/.*\\.js","name":"eProof","id":"462"},
{"type":"ad","aid":"264","cid":"328","pattern":"(autocontext|o)\\.begun\\.ru\\/","name":"Begun","id":"463"},
{"type":"tracker","aid":"265","cid":"330","pattern":"foresee-(trigger(.*)?|alive|analytics(.*)?)\\.js","name":"ForeSee","id":"464"},
{"type":"tracker","aid":"266","cid":"331","pattern":"\\.quintelligence\\.com/quint\\.js","name":"Quintelligence","id":"465"},
{"type":"tracker","aid":"267","cid":"332","pattern":"3dstats\\.com\\/cgi-bin\\/3dstrack(ssl)?\\.cgi","name":"3DStats","id":"466"},
{"type":"tracker","aid":"268","cid":"332","pattern":"addfreestats\\.com\\/cgi-bin\\/afstrack\\.cgi","name":"AddFreeStats","id":"467"},
{"type":"tracker","aid":"269","cid":"335","pattern":"(\\.webtrekk\\.net|\\/webtrekk\\.js)","name":"Webtrekk","id":"468"},
{"type":"ad","aid":"270","cid":"336","pattern":"(cts(-secure)?\\.channelintelligence\\.com\\/[0-9]*_landing\\.js|cts-log\\.channelintelligence\\.com\\/)","name":"Channel Intelligence","id":"470"},
{"type":"tracker","aid":"272","cid":"337","pattern":"ads\\.doclix\\.com\\/adserver\\/serve\\/","name":"AdSide","id":"471"},
{"type":"tracker","aid":"273","cid":"338","pattern":"bdv\\.bidvertiser\\.com\\/","name":"BidVertiser","id":"472"},
{"type":"tracker","aid":"274","cid":"339","pattern":"view\\.binlayer\\.com\\/ad","name":"BinLayer","id":"473"},
{"type":"tracker","aid":"275","cid":"340","pattern":"get\\.mirando\\.de\\/","name":"Mirando","id":"474"},
{"type":"tracker","aid":"276","cid":"341","pattern":"ads\\.adtiger\\.de\\/","name":"AdTiger","id":"475"},
{"type":"tracker","aid":"277","cid":"342","pattern":"js\\.adscale\\.de\\/","name":"AdScale","id":"476"},
{"type":"tracker","aid":"279","cid":"345","pattern":"dsa\\.csdata1\\.com","name":"ClearSaleing","id":"477"},
{"type":"tracker","aid":"278","cid":"344","pattern":"(js|tag)\\.admeld\\.com","name":"AdMeld","id":"478"},
{"type":"tracker","aid":"280","cid":"346","pattern":"cdn\\.wibiya\\.com\\/(toolbars|loaders)","name":"Wibiya Toolbar","id":"479"},
{"type":"ad","aid":"281","cid":"349","pattern":"\\/adam\\/(cm8[0-9a-z_]+\\.js|detect)","name":"CheckM8","id":"480"},
{"type":"tracker","aid":"282","cid":"350","pattern":"www\\.actonsoftware\\.com\\/acton\\/bn\\/","name":"Act-On Beacon","id":"481"},
{"type":"tracker","aid":"283","cid":"351","pattern":"(\\.res-x\\.com\\/ws\\/r2\\/resonance|\\/resxclsa\\.js)","name":"Resonance","id":"483"},
{"type":"tracker","aid":"284","cid":"353","pattern":"(\\/gomez.+?\\.js|\\.[rt]\\.axf8\\.net\\/)","name":"Gomez","id":"484"},
{"type":"tracker","aid":"285","cid":"354","pattern":"(cdn\\.mercent\\.com\\/js\\/tracker\\.js|link\\.mercent\\.com\\/)","name":"Mercent","id":"485"},
{"type":"ad","aid":"287","cid":"282","pattern":"(\\.content\\.ru4\\.com\\/images\\/|\\.edge\\.ru4\\.com\\/smartserve\\/|\\.xp1\\.ru4\\.com\\/|ad\\.xplusone\\.com\\/|\\/xplus1\\/xp1\\.js)","name":"[x+1]","id":"487"},
{"type":"tracker","aid":"288","cid":"355","pattern":"www\\.googleadservices\\.com\\/pagead\\/conversion","name":"Google AdWords Conversion","id":"488"},
{"type":"tracker","aid":"289","cid":"362","pattern":"s\\.clickability\\.com\\/s","name":"Clickability Beacon","id":"490"},
{"type":"tracker","aid":"290","cid":"13","pattern":"(xslt\\.alexa\\.com\\/site_stats\\/js\\/s\\/|widgets\\.alexa\\.com\\/traffic\\/javascript\\/)","name":"Alexa Widget","id":"491"},
{"type":"tracker","aid":"291","cid":"363","pattern":"ad\\.retargeter\\.com/seg","name":"ReTargeter Beacon","id":"492"},
{"type":"tracker","aid":"292","cid":"364","pattern":"tags\\.mediaforge\\.com\\/if\\/[0-9]+","name":"mediaFORGE","id":"494"},
{"type":"tracker","aid":"293","cid":"365","pattern":"((targeting\\.api|widgets-ak)\\.visualdna\\.com|\\.visualdna\\.com\\/(live|js)|\\.visualdna-stats\\.com)\\/","name":"VisualDNA","id":"496"},
{"type":"tracker","aid":"256","cid":"375","pattern":"pixel\\.33across\\.com","name":"33Across","id":"498"},
{"type":"tracker","aid":"294","cid":"367","pattern":"tracking\\.searchmarketing\\.com\\/","name":"ChannelAdvisor","id":"499"},
{"type":"tracker","aid":"295","cid":"368","pattern":"saas\\.intelligencefocus\\.com\\/sensor\\/","name":"IntelligenceFocus","id":"501"},
{"type":"tracker","aid":"296","cid":"368","pattern":"www\\.domodomain\\.com\\/domodomain\\/sensor\\/","name":"DomoDomain","id":"502"},
{"type":"tracker","aid":"297","cid":"372","pattern":"(es|by\\.essl)\\.optimost.com\\/(es\\/[0-9]+\\/c\\/[0-9]+\\/u\\/[a-zA-Z_]+\\.js|(by\\/)?trial\\/)","name":"Optimost","id":"504"},
{"type":"ad","aid":"299","cid":"257","pattern":"\\/(html|image|js)\\.ng\\/","name":"DoubleClick DART","id":"505"},
{"type":"tracker","aid":"300","cid":"373","pattern":"t\\.p\\.mybuys\\.com\\/js\\/mybuys3\\.js","name":"MyBuys","id":"506"},
{"type":"ad","aid":"301","cid":"265","pattern":"track\\.roiservice\\.com\\/track\\/","name":"Atlas ProfitBuilder","id":"507"},
{"type":"ad","aid":"302","cid":"293","pattern":"(bh|tag|ds)\\.contextweb\\.com","name":"ContextWeb","id":"508"},
{"type":"tracker","aid":"304","cid":"374","pattern":"\\.dmtracker\\.com\\/","name":"DemandMedia","id":"509"},
{"type":"tracker","aid":"306","cid":"376","pattern":"cdn\\.triggertag\\.gorillanation\\.com\\/js\\/triggertag\\.js","name":"Gorilla Nation","id":"511"},
{"type":"tracker","aid":"307","cid":"377","pattern":"nr7\\.us\\/apps\\/","name":"Net-Results","id":"512"},
{"type":"tracker","aid":"308","cid":"378","pattern":"searchignite\\.com\\/si\\/cm\\/tracking\\/","name":"SearchIgnite","id":"514"},
{"type":"tracker","aid":"309","cid":"183","pattern":"\\.wa\\.marketingsolutions\\.yahoo\\.com\\/script\\/scriptservlet","name":"Yahoo Search Marketing Analytics","id":"516"},
{"type":"ad","aid":"310","cid":"257","pattern":"\\.doubleclick\\.net\\/activityi","name":"DoubleClick Floodlight","id":"517"},
{"type":"tracker","aid":"311","cid":"379","pattern":"prof\\.estat\\.com\\/js\\/","name":"eStat","id":"518"},
{"type":"tracker","aid":"312","cid":"380","pattern":"(adstat\\.4u\\.pl\\/s\\.js|stat\\.4u\\.pl\\/cgi-bin\\/)","name":"stat4u","id":"519"},
{"type":"tracker","aid":"313","cid":"381","pattern":"\\.hit\\.gemius\\.pl","name":"Gemius","id":"520"},
{"type":"tracker","aid":"314","cid":"382","pattern":"jlinks\\.industrybrains\\.com\\/jsct","name":"Adhere","id":"521"},
{"type":"tracker","aid":"315","cid":"383","pattern":"z(i|a)g\\.(js|gif)","name":"ZigZag","id":"522"},
{"type":"tracker","aid":"316","cid":"384","pattern":"bs\\.serving-sys\\.com\\/burstingpipe\\/(activityserver|adserver)\\.bs","name":"MediaMind","id":"523"},
{"type":"tracker","aid":"318","cid":"322","pattern":"segment-pixel\\.invitemedia\\.com","name":"Invite Media","id":"525"},
{"type":"tracker","aid":"319","cid":"385","pattern":"assets\\.newsinc\\.com\\/(ndn\\.2\\.js|analyticsprovider\\.svc\\/)","name":"NDN Analytics","id":"526"},
{"type":"tracker","aid":"320","cid":"386","pattern":"\\.predictad\\.com\\/scripts\\/(molosky|publishers)\\/","name":"PredictAd","id":"527"},
{"type":"tracker","aid":"321","cid":"387","pattern":"(track|files)\\.netshelter\\.net","name":"NetShelter","id":"528"},
{"type":"tracker","aid":"322","cid":"388","pattern":"\\.iesnare\\.com","name":"ReputationManager","id":"529"},
{"type":"tracker","aid":"323","cid":"396","pattern":"cdn(s?)\\.(brcdn|brsrvr)\\.com\\/v1\\/br-trk\\.js","name":"BloomReach","id":"531"},
{"type":"tracker","aid":"324","cid":"397","pattern":"(beacon|js)\\.clickequations\\.net","name":"ClickEquations","id":"532"},
{"type":"tracker","aid":"326","cid":"398","pattern":"mct\\.rkdms\\.com\\/sid\\.gif","name":"RKG Attribution Management","id":"533"},
{"type":"tracker","aid":"327","cid":"399","pattern":"server[2-4]\\.web-stat\\.com","name":"Web-Stat","id":"535"},
{"type":"tracker","aid":"328","cid":"400","pattern":"\\/internal\\/jscript\\/dwanalytics\\.js","name":"Demandware Analytics","id":"537"},
{"type":"tracker","aid":"329","cid":"401","pattern":"a\\.giantrealm\\.com","name":"Giant Realm","id":"538"},
{"type":"tracker","aid":"330","cid":"403","pattern":"tags\\.dashboardad\\.net","name":"Dashboard Ad","id":"540"},
{"type":"tracker","aid":"331","cid":"404","pattern":"\\.oewabox\\.at","name":"OWA","id":"541"},
{"type":"tracker","aid":"332","cid":"262","pattern":"\\.amgdgt\\.com\\/(ads|base)\\/","name":"Adconion","id":"542"},
{"type":"tracker","aid":"317","cid":"272","pattern":"img\\.pulsemgr\\.com","name":"Permuto","id":"543"},
{"type":"tracker","aid":"333","cid":"348","pattern":"(ads|image2)\\.pubmatic\\.com\\/adserver\\/","name":"PubMatic","id":"544"},
{"type":"tracker","aid":"334","cid":"405","pattern":"ad\\.fed\\.adecn\\.com","name":"AdECN","id":"546"},
{"type":"tracker","aid":"335","cid":"406","pattern":"adelixir\\.com\\/(webpages\\/scripts\\/ne_roi_tracking\\.js|neroitrack)","name":"LXR100","id":"547"},
{"type":"tracker","aid":"336","cid":"408","pattern":"keywordmax\\.com\\/tracking\\/","name":"KeywordMax","id":"548"},
{"type":"tracker","aid":"337","cid":"409","pattern":"amadesa\\.com\\/static\\/client_js\\/engine\\/amadesajs\\.js","name":"Amadesa","id":"550"},
{"type":"tracker","aid":"338","cid":"410","pattern":"\\.srtk\\.net\\/www\\/delivery\\/","name":"SearchRev","id":"551"},
{"type":"tracker","aid":"339","cid":"411","pattern":"(tns-counter\\.ru|tns-counter\\.js|\\.tns-cs\\.net|statistik-gallup\\.net)","name":"TNS","id":"552"},
{"type":"tracker","aid":"340","cid":"412","pattern":"[a|c]\\.adroll\\.com","name":"AdRoll","id":"553"},
{"type":"tracker","aid":"341","cid":"413","pattern":"hints\\.netflame\\.cc\\/service\\/script\\/","name":"Fireclick","id":"554"},
{"type":"tracker","aid":"343","cid":"176","pattern":"\\.tynt\\.com\\/ts\\.js","name":"Tynt SpeedSearch","id":"555"},
{"type":"tracker","aid":"344","cid":"415","pattern":"ad\\.xtendmedia\\.com","name":"XTEND","id":"556"},
{"type":"tracker","aid":"345","cid":"416","pattern":"newstogram\\.com\\/(.*)\\/(histogram|toolbar)\\.js","name":"Newstogram","id":"558"},
{"type":"tracker","aid":"346","cid":"417","pattern":"ad\\.adlegend\\.com","name":"TruEffect","id":"559"},
{"type":"tracker","aid":"347","cid":"418","pattern":"/a\\.mouseflow\\.com","name":"Mouseflow","id":"560"},
{"type":"tracker","aid":"348","cid":"419","pattern":"(rotator\\.adjuggler\\.com|\\/banners\\/ajtg\\.js|\\/servlet\\/ajrotator\\/)","name":"AdJuggler","id":"561"},
{"type":"tracker","aid":"349","cid":"420","pattern":"picadmedia\\.com\\/js\\/","name":"Image Space Media","id":"562"},
{"type":"tracker","aid":"350","cid":"421","pattern":"(m|js|api|cdn)\\.viglink\\.com","name":"VigLink","id":"563"},
{"type":"tracker","aid":"351","cid":"422","pattern":"sageanalyst\\.net","name":"SageMetrics","id":"565"},
{"type":"tracker","aid":"352","cid":"423","pattern":"svlu\\.net","name":"SeeVolution","id":"566"},
{"type":"tracker","aid":"353","cid":"292","pattern":"w55c\\.net","name":"DataXu","id":"567"},
{"type":"tracker","aid":"354","cid":"395","pattern":"(cdn|crosspixel)\\.demdex\\.net","name":"Demdex","id":"569"},
{"type":"tracker","aid":"355","cid":"424","pattern":"adserver\\.(adtechus\\.com|adtech\\.de)","name":"ADTECH","id":"570"},
{"type":"tracker","aid":"356","cid":"112","pattern":"\\.r\\.msn\\.com\\/scripts\\/microsoft_adcenterconversion\\.js","name":"Microsoft adCenter Conversion","id":"571"},
{"type":"tracker","aid":"357","cid":"425","pattern":"(dw|adlog)\\.com\\.com\\/","name":"CBS Interactive","id":"572"},
{"type":"tracker","aid":"358","cid":"298","pattern":"netmng\\.com\\/","name":"Netmining","id":"573"},
{"type":"tracker","aid":"359","cid":"321","pattern":"px\\.owneriq\\.net","name":"OwnerIQ","id":"574"},
{"type":"tracker","aid":"360","cid":"426","pattern":"app\\.insightgrit\\.com\\/1\\/","name":"Zeta Search","id":"575"},
{"type":"tracker","aid":"361","cid":"428","pattern":"ads\\.bridgetrack\\.com\\/","name":"BridgeTrack","id":"576"},
{"type":"tracker","aid":"363","cid":"576","pattern":"hits\\.convergetrack\\.com\\/","name":"ConvergeTrack","id":"578"},
{"type":"tracker","aid":"364","cid":"577","pattern":"(\\.dt07\\.net|mg\\.dt00\\.net\\/(u)?js)","name":"MarketGid","id":"580"},
{"type":"tracker","aid":"365","cid":"578","pattern":"(publishers|\\.hat)\\.halogennetwork\\.com\\/","name":"Halogen Network","id":"581"},
{"type":"tracker","aid":"366","cid":"579","pattern":"app\\.phonalytics\\.com\\/track","name":"Phonalytics","id":"582"},
{"type":"tracker","aid":"367","cid":"499","pattern":"cn\\.clickable\\.net\\/js\\/cct\\.js","name":"Clickable","id":"583"},
{"type":"tracker","aid":"368","cid":"488","pattern":"s0b?\\.bluestreak\\.com\\/ix\\.e","name":"BlueStreak","id":"584"},
{"type":"tracker","aid":"369","cid":"582","pattern":"tracking\\.dsmmadvantage\\.com\\/clients\\/","name":"DSMM Advantage","id":"585"},
{"type":"tracker","aid":"370","cid":"572","pattern":"(cdn\\.nprove\\.com\\/npcore\\.js|go\\.cpmadvisors\\.com\\/)","name":"XA.net","id":"586"},
{"type":"tracker","aid":"371","cid":"445","pattern":"(tracking\\.intermundomedia\\.com|ad\\.intermundonet\\.com|media\\.intermundomedia\\.com\\/([ij]pixel|trutags|ping))","name":"InterMundo Media","id":"587"},
{"type":"tracker","aid":"372","cid":"584","pattern":"vtracker\\.com\\/(counter|stats|tr\\.x|ts|tss|mvlive|digits)","name":"MindViz Tracker","id":"588"},
{"type":"tracker","aid":"373","cid":"585","pattern":"(scripts|tm)\\.verticalacuity\\.com\\/vat\\/mon\\/vt\\.js","name":"Vertical Acuity","id":"590"},
{"type":"tracker","aid":"374","cid":"586","pattern":"(impression|ca)\\.clickinc\\.com\\/","name":"ClickInc","id":"591"},
{"type":"tracker","aid":"375","cid":"587","pattern":"(\\.skimresources\\.com\\/js|\\.skimlinks\\.com\\/(api|js)\\/)","name":"SkimLinks","id":"592"},
{"type":"tracker","aid":"376","cid":"588","pattern":"ad\\.metanetwork\\.com\\/","name":"Meta Network","id":"593"},
{"type":"tracker","aid":"377","cid":"589","pattern":"rt\\.legolas-media\\.com\\/","name":"Legolas Media","id":"595"},
{"type":"tracker","aid":"378","cid":"447","pattern":"cdn\\.krxd\\.net\\/krux\\.js","name":"Krux Digital","id":"597"},
{"type":"tracker","aid":"379","cid":"80","pattern":"(clickserve\\.cc-dt\\.com\\/link\\/|gan\\.doubleclick\\.net\\/gan)","name":"Google Affiliate Network","id":"598"},
{"type":"tracker","aid":"380","cid":"516","pattern":"\\.fwmrm\\.net\\/(ad|g)\\/","name":"FreeWheel","id":"599"},
{"type":"tracker","aid":"381","cid":"590","pattern":"\\.ibpxl\\.com\\/","name":"InternetBrands","id":"602"},
{"type":"tracker","aid":"382","cid":"591","pattern":"pmetrics\\.performancing\\.com\\/(js|in\\.php|[0-9]*\\.js)","name":"Performancing Metrics","id":"603"},
{"type":"tracker","aid":"383","cid":"592","pattern":"(tracking\\.conversionlab\\.it|conversionlab\\.trackset\\.com\\/track\\/)","name":"Trackset ConversionLab","id":"604"},
{"type":"tracker","aid":"384","cid":"592","pattern":"visualpath[0-9]\\.trackset\\.it\\/","name":"Trackset VisualPath","id":"605"},
{"type":"tracker","aid":"385","cid":"452","pattern":"(cdn\\.adblade\\.com\\/js\\/|(web|pixel)\\.adblade\\.com\\/imps\\.php)","name":"Adblade","id":"606"},
{"type":"tracker","aid":"386","cid":"269","pattern":"ads\\.undertone\\.com","name":"Undertone Networks","id":"608"},
{"type":"tracker","aid":"387","cid":"531","pattern":"ads\\.lucidmedia\\.com\\/clicksense\\/pixel","name":"Lucid Media","id":"610"},
{"type":"tracker","aid":"388","cid":"505","pattern":"track\\.did-it\\.com\\/","name":"Didit Maestro","id":"612"},
{"type":"tracker","aid":"389","cid":"505","pattern":"tag\\.didit\\.com\\/(didit|js)\\/","name":"Didit Blizzard","id":"613"},
{"type":"tracker","aid":"390","cid":"268","pattern":"(content|track)\\.pulse360\\.com\\/","name":"Pulse360","id":"614"},
{"type":"tracker","aid":"391","cid":"433","pattern":"\\.adgear\\.com\\/","name":"AdGear","id":"615"},
{"type":"tracker","aid":"392","cid":"596","pattern":"j\\.clickdensity.com\\/cr\\.js","name":"ClickDensity","id":"616"},
{"type":"tracker","aid":"393","cid":"593","pattern":"visitorville\\.com\\/js\\/plgtrafic\\.js\\.php","name":"VisitorVille","id":"618"},
{"type":"tracker","aid":"394","cid":"594","pattern":"ads\\.affbuzzads\\.com\\/","name":"AffiliateBuzz","id":"619"},
{"type":"tracker","aid":"395","cid":"597","pattern":"cts\\.vresp\\.com\\/s\\.gif","name":"VerticalResponse","id":"620"},
{"type":"tracker","aid":"396","cid":"529","pattern":"(ad(network)?|click)\\.linksynergy\\.com","name":"LinkShare","id":"621"},
{"type":"tracker","aid":"397","cid":"600","pattern":"websitealive[0-9]\\.com\\/","name":"AliveChat","id":"622"},
{"type":"tracker","aid":"398","cid":"601","pattern":"b\\.monetate\\.net\\/js\\/","name":"Monetate","id":"624"},
{"type":"tracker","aid":"399","cid":"559","pattern":"(adserver|int)\\.teracent\\.net\\/","name":"Teracent","id":"625"},
{"type":"tracker","aid":"400","cid":"307","pattern":"html\\.aggregateknowledge\\.com\\/iframe","name":"Aggregate Knowledge","id":"627"},
{"type":"tracker","aid":"401","cid":"558","pattern":"\\.tellapart\\.com\\/crumb","name":"TellApart","id":"629"},
{"type":"tracker","aid":"402","cid":"439","pattern":"vitamine\\.networldmedia\\.net\\/bts\\/","name":"BV! Media","id":"630"},
{"type":"tracker","aid":"403","cid":"602","pattern":"projectwonderful\\.com/(\\ad_display\\.js|gen\\.php)","name":"Project Wonderful","id":"632"},
{"type":"tracker","aid":"404","cid":"45","pattern":"voicefive\\.com\\/.*\\.pli","name":"VoiceFive","id":"633"},
{"type":"tracker","aid":"405","cid":"603","pattern":"(econda.*\\.js|www\\.econda-monitor\\.de\\/els\\/logging)","name":"Econda","id":"635"},
{"type":"tracker","aid":"406","cid":"435","pattern":"adspeed\\.(com|net)\\/ad\\.php","name":"AdSpeed","id":"636"},
{"type":"tracker","aid":"407","cid":"616","pattern":"(live1\\.netupdater\\.info\\/live\\.php|netupdater[0-9]\\.de|\\/netupdater(_live)?)","name":"NetUpdater","id":"638"},
{"type":"tracker","aid":"408","cid":"620","pattern":"\\.ic-live\\.com\\/(goat\\.php|[0-9][0-9][0-9][0-9]\\.js)","name":"iCrossing","id":"639"},
{"type":"tracker","aid":"409","cid":"308","pattern":"adreadytractions\\.com\\/rt\\/","name":"AdReady","id":"640"},
{"type":"tracker","aid":"47","cid":"1","pattern":"ad\\.yieldmanager\\.com\\/pixel","name":"Right Media","id":"642"},
{"type":"tracker","aid":"410","cid":"648","pattern":"(adcode|conv)\\.adengage\\.com","name":"AdEngage","id":"643"},
{"type":"ad","aid":"411","cid":"647","pattern":"server\\.cpmstar\\.com","name":"CPMStar","id":"645"},
{"type":"tracker","aid":"412","cid":"646","pattern":"tracker\\.financialcontent\\.com\\/","name":"Financial Content","id":"647"},
{"type":"tracker","aid":"413","cid":"645","pattern":"www\\.csm-secure\\.com\\/scripts\\/clicktracking\\.js","name":"ClearSearch","id":"648"},
{"type":"tracker","aid":"414","cid":"644","pattern":"sitecompass\\.com\\/(sc_cap\\/|[ij]pixel)","name":"Site Compass","id":"649"},
{"type":"tracker","aid":"415","cid":"643","pattern":"link\\.ixs1\\.net\\/s\\/at","name":"eWayDirect","id":"651"},
{"type":"tracker","aid":"416","cid":"642","pattern":"upsellit\\.com\\/(upsellit(.*)?\\.jsp|custom\\/)","name":"UpSellit","id":"652"},
{"type":"tracker","aid":"420","cid":"430","pattern":"accelerator-media\\.com\\/pixel","name":"Accelerator Media","id":"653"},
{"type":"tracker","aid":"421","cid":"571","pattern":"(haku|puma|cheetah)\\.vizu\\.com","name":"Vizu","id":"655"},
{"type":"tracker","aid":"422","cid":"669","pattern":"\\.adfox\\.ru\\/preparecode","name":"AdFox","id":"657"},
{"type":"tracker","aid":"423","cid":"683","pattern":"(goku\\.brightcove\\.com|admin\\.brightcove\\.com\\/js)","name":"Brightcove","id":"658"},
{"type":"tracker","aid":"425","cid":"290","pattern":"\\.mathtag\\.com","name":"MediaMath","id":"662"},
{"type":"tracker","aid":"426","cid":"672","pattern":"((ad2|counter)\\.rambler\\.ru|\\.mail\\.ru\\/counter|\\.list\\.ru\\/counter)","name":"Rambler","id":"664"},
{"type":"tracker","aid":"427","cid":"670","pattern":"lookup\\.bluecava\\.com","name":"BlueCava","id":"665"},
{"type":"tracker","aid":"428","cid":"671","pattern":"(monitus(_tools)?\\.js|(l|b)ive\\.monitus\\.net)","name":"Monitus","id":"667"},
{"type":"tracker","aid":"429","cid":"598","pattern":"service\\.optify\\.net\\/(visit/ping|opt\\.js)","name":"Optify","id":"668"},
{"type":"ad","aid":"430","cid":"599","pattern":"ad\\.reduxmedia\\.com\\/","name":"Redux Media","id":"670"},
{"type":"tracker","aid":"431","cid":"622","pattern":"(servedby|geo)\\.precisionclick\\.com\\/(ad|midas)","name":"PrecisionClick","id":"672"},
{"type":"ad","aid":"41","cid":"257","pattern":"destinationurl\\.com","name":"DoubleClick","id":"674"},
{"type":"tracker","aid":"432","cid":"517","pattern":"counters\\.gigya\\.com","name":"Gigya Beacon","id":"675"},
{"type":"tracker","aid":"433","cid":"690","pattern":"webiqonline\\.com","name":"Usability Sciences WebIQ","id":"676"},
{"type":"tracker","aid":"434","cid":"691","pattern":"radar\\.cedexis\\.(com|net)","name":"Cedexis Radar","id":"677"},
{"type":"tracker","aid":"435","cid":"688","pattern":"as00\\.estara\\.com\\/as\\/initiatecall2\\.php","name":"ATG Optimization","id":"678"},
{"type":"tracker","aid":"438","cid":"688","pattern":"\\.atgsvcs\\.com\\/js\\/atgsvcs\\.js","name":"ATG Recommendations","id":"679"},
{"type":"tracker","aid":"439","cid":"614","pattern":"\\.mookie1\\.com","name":"Media Innovation Group","id":"680"},
{"type":"tracker","aid":"440","cid":"686","pattern":"stats\\.businessol\\.com","name":"BusinessOnLine Analytics","id":"682"},
{"type":"tracker","aid":"441","cid":"687","pattern":"(webtraxs\\.js|webtraxs\\.com\\/(trxscript|webtraxs)\\.php)","name":"Web Traxs","id":"683"},
{"type":"tracker","aid":"442","cid":"453","pattern":"pixel\\.adbuyer\\.com","name":"AdBuyer.com","id":"684"},
{"type":"tracker","aid":"443","cid":"557","pattern":"adadvisor\\.net","name":"TargusInfo","id":"686"},
{"type":"tracker","aid":"444","cid":"693","pattern":"vertster.com\\/.*\\/vswap\\.js","name":"Vertster","id":"688"},
{"type":"tracker","aid":"445","cid":"695","pattern":"voice2page\\.com\\/naa_1x1\\.js","name":"InternetAudioAds","id":"689"},
{"type":"tracker","aid":"446","cid":"678","pattern":"ad\\.z5x\\.net","name":"DSNR Media Group","id":"690"},
{"type":"tracker","aid":"447","cid":"694","pattern":"data\\.resultlinks\\.com","name":"Result Links","id":"692"},
{"type":"tracker","aid":"448","cid":"512","pattern":"eyewonder\\.com\\/.*\\/wrapper\\.js","name":"EyeWonder","id":"693"},
{"type":"tracker","aid":"449","cid":"624","pattern":"ad(media)?\\.wsod\\.com","name":"Wall Street on Demand","id":"694"},
{"type":"tracker","aid":"424","cid":"266","pattern":"ats\\.tumri\\.net","name":"Tumri","id":"698"},
{"type":"tracker","aid":"450","cid":"569","pattern":"\\.visiblemeasures\\.com\\/log","name":"Visible Measures","id":"699"},
{"type":"tracker","aid":"451","cid":"698","pattern":"fx\\.gtop(stats\\.com|\\.ro)\\/js\\/gtop\\.js","name":"GTop","id":"701"},
{"type":"tracker","aid":"452","cid":"513","pattern":"adsfac\\.(eu|us|sg|net)","name":"Facilitate Digital","id":"702"},
{"type":"tracker","aid":"453","cid":"710","pattern":"pixazza\\.com\\/(static\\/)?widget","name":"Pixazza","id":"704"},
{"type":"tracker","aid":"454","cid":"704","pattern":"(qnsr\\.com|thecounter\\.com\\/id)","name":"Quinn Street","id":"705"},
{"type":"tracker","aid":"455","cid":"159","pattern":"(adviva\\.net|(smp|leads)\\.specificmedia\\.com)","name":"Specific Media","id":"707"},
{"type":"tracker","aid":"456","cid":"274","pattern":"gmads\\.net","name":"GroupM Server","id":"709"},
{"type":"tracker","aid":"457","cid":"556","pattern":"levexis\\.com","name":"TagMan","id":"711"},
{"type":"tracker","aid":"458","cid":"733","pattern":"(mmcore\\.js|cg-global\\.maxymiser\\.com)","name":"Maxymiser","id":"713"},
{"type":"tracker","aid":"459","cid":"728","pattern":"nexus\\.ensighten\\.com","name":"Ensighten","id":"714"},
{"type":"tracker","aid":"460","cid":"729","pattern":"uptrends\\.com\\/(aspx\\/uptime\\.aspx|images\\/uptrends\\.gif)","name":"Uptrends","id":"715"},
{"type":"tracker","aid":"461","cid":"730","pattern":"visitstreamer\\.com\\/vs\\.js","name":"Visit Streamer","id":"716"},
{"type":"tracker","aid":"462","cid":"732","pattern":"crm-metrix\\.com","name":"crmmetrix","id":"717"},
{"type":"tracker","aid":"463","cid":"731","pattern":"utd\\.stratigent\\.com","name":"Stratigent","id":"718"},
{"type":"tracker","aid":"464","cid":"249","pattern":"(facebook\\.com\\/(plugins|widgets)\\/(like|likebox|activity|recommendations|facepile)\\.php|fbcdn\\.net\\/connect\\.php\\/js\\/fb\\.share)","name":"Facebook Social Plugins","id":"719"},
{"type":"tracker","aid":"465","cid":"494","pattern":"((conversions|c|p)\\.chango\\.(ca|com)|(as|adunit)?\\.chango\\.(ca|com)\\/links)","name":"Chango","id":"720"},
{"type":"tracker","aid":"466","cid":"564","pattern":"cdna\\.tremormedia\\.com","name":"Tremor Media","id":"722"},
{"type":"tracker","aid":"467","cid":"504","pattern":"admonkey\\.dapper\\.net","name":"Dapper","id":"723"},
{"type":"tracker","aid":"468","cid":"699","pattern":"p-td\\.com","name":"Accuen Media","id":"724"},
{"type":"tracker","aid":"469","cid":"286","pattern":"yieldoptimizer\\.com","name":"Adara Media","id":"726"},
{"type":"tracker","aid":"470","cid":"318","pattern":"displaymarketplace\\.com","name":"Datran","id":"728"},
{"type":"tracker","aid":"471","cid":"573","pattern":"ads\\.addynamix\\.com\\/category","name":"Ybrant Media","id":"732"},
{"type":"tracker","aid":"472","cid":"502","pattern":"(dd|ff)\\.connextra\\.com","name":"Connextra","id":"734"},
{"type":"tracker","aid":"473","cid":"738","pattern":"(api|apps)\\.conduit\\.com","name":"Conduit","id":"736"},
{"type":"tracker","aid":"474","cid":"748","pattern":"udmserve\\.net","name":"Underdog Media","id":"738"},
{"type":"tracker","aid":"475","cid":"749","pattern":"pixel\\.adpredictive\\.com","name":"AdPredictive","id":"740"},
{"type":"tracker","aid":"476","cid":"751","pattern":"px\\.steelhousemedia\\.com","name":"Steel House Media","id":"742"},
{"type":"tracker","aid":"477","cid":"752","pattern":"tracking\\.godatafeed\\.com","name":"GoDataFeed","id":"744"},
{"type":"tracker","aid":"478","cid":"753","pattern":"/trumba\\.com\\/scripts\\/spuds\\.js","name":"Trumba","id":"745"},
{"type":"tracker","aid":"479","cid":"747","pattern":"adspaces\\.ero-advertising\\.com","name":"EroAdvertising","id":"746"},
{"type":"tracker","aid":"481","cid":"755","pattern":"ads\\.adxpansion\\.com","name":"AdXpansion","id":"747"},
{"type":"tracker","aid":"482","cid":"757","pattern":"clarity\\.adinsight\\.eu\\/static\\/adinsight","name":"AdInsight Clarity","id":"748"},
{"type":"tracker","aid":"483","cid":"756","pattern":"\\/performable\\/pax\\.js","name":"Performable","id":"749"},
{"type":"tracker","aid":"484","cid":"758","pattern":"snapabug\\.appspot\\.com\\/snapabug","name":"SnapEngage","id":"750"},
{"type":"tracker","aid":"485","cid":"754","pattern":"breathe\\.c3metrics\\.com","name":"C3 Metrics","id":"751"},
{"type":"tracker","aid":"486","cid":"550","pattern":"um\\.simpli\\.fi\\/ab_match","name":"Simpli.fi","id":"752"},
{"type":"tracker","aid":"487","cid":"740","pattern":"dt\\.admission\\.net\\/retargeting\\/displaytracker\\.js","name":"Cobalt Group","id":"754"},
{"type":"tracker","aid":"488","cid":"281","pattern":"yumenetworks\\.com\\/dynamic","name":"YuMe, Inc.","id":"755"},
{"type":"tracker","aid":"489","cid":"739","pattern":"trk\\.vindicosuite\\.com\\/Tracking\\/","name":"Vindico Group","id":"758"},
{"type":"tracker","aid":"490","cid":"565","pattern":"creativeby2\\.unicast\\.com\\/(assets|script2)","name":"Unicast","id":"760"},
{"type":"tracker","aid":"491","cid":"446","pattern":"(hs|sw)\\.interpolls\\.com\\/(imprimage\\.poll?|inter|cache|creative|redir)","name":"Interpolls","id":"763"},
{"type":"tracker","aid":"492","cid":"673","pattern":"rs\\.gwallet\\.com\\/r1\\/pixel","name":"RadiumOne","id":"766"},
{"type":"tracker","aid":"493","cid":"366","pattern":"wtp101\\.com\\/","name":"Adnetik","id":"768"},
{"type":"tracker","aid":"494","cid":"475","pattern":"(this\\.content\\.served\\.by|media2)\\.adshuffle\\.com\\/(p\\/|asrefinc11\\.js)","name":"AdShuffle","id":"769"},
{"type":"tracker","aid":"495","cid":"442","pattern":"(servedby|stat|cdn|a)\\.flashtalking\\.com\\/((tags|report)v[0-9]|imp|[0-9][0-9][0-9][0-9])\\/","name":"Flashtalking","id":"771"},
{"type":"tracker","aid":"496","cid":"477","pattern":"(servedby|ads|event)\\.adxpose\\.com\\/(event\\.flow?|ads\\/ads\\.js?uid=|adxpose\\/find_ad\\.js)","name":"AdXpose","id":"773"},
{"type":"tracker","aid":"505","cid":"662","pattern":"utag\\.loader\\.js","name":"Tealium","id":"812"},
{"type":"tracker","aid":"506","cid":"509","pattern":"(us\\.img|ads)\\.e-planning\\.net","name":"e-planning","id":"814"},
{"type":"tracker","aid":"507","cid":"775","pattern":"choices\\.truste\\.com\\/ca","name":"TRUSTe Notice","id":"816"},
{"type":"tracker","aid":"508","cid":"761","pattern":"btstatic\\.com","name":"BrightTag","id":"817"},
{"type":"tracker","aid":"509","cid":"778","pattern":"tldadserv\\.com\\/impopup\\.php","name":"TLDAdserv","id":"818"},
{"type":"tracker","aid":"510","cid":"779","pattern":"wiredminds\\.de\\/track","name":"WiredMinds","id":"819"},
{"type":"tracker","aid":"500","cid":"491","pattern":"segs\\.btrll\\.com\\/v[0-9]\\/tpix\\/","name":"BrightRoll","id":"820"},
{"type":"tracker","aid":"511","cid":"492","pattern":"p\\.brilig\\.com\\/contact\\/bct?pid","name":"Brilig","id":"821"},
{"type":"tracker","aid":"512","cid":"538","pattern":"xcdn\\.xgraph\\.net\\/([0-9]|partner\\.js)","name":"XGraph","id":"823"},
{"type":"tracker","aid":"513","cid":"58","pattern":"cdn\\.doubleverify\\.com\\/oba","name":"DoubleVerify Notice","id":"825"},
{"type":"tracker","aid":"516","cid":"436","pattern":"beencounter\\.com/b\\.js","name":"Beencounter","id":"828"},
{"type":"tracker","aid":"517","cid":"563","pattern":"traveladvertising\\.com\\/live\\/tan","name":"Travel Ad Network","id":"831"},
{"type":"tracker","aid":"518","cid":"506","pattern":"everestjs\\.net|pixel([0-9]*)?\\.everesttech\\.net","name":"Efficient Frontier","id":"833"},
{"type":"tracker","aid":"520","cid":"606","pattern":"ctasnet\\.com","name":"Crimtan","id":"836"},
{"type":"tracker","aid":"522","cid":"547","pattern":"raasnet\\.com","name":"Red Aril","id":"839"},
{"type":"tracker","aid":"523","cid":"511","pattern":"eyereturn\\.com","name":"eyeReturn Marketing","id":"841"},
{"type":"tracker","aid":"524","cid":"617","pattern":"rainbow\\.mythings\\.com","name":"My Things Media","id":"843"},
{"type":"tracker","aid":"525","cid":"659","pattern":"esm1\\.net","name":"Think Realtime","id":"845"},
{"type":"tracker","aid":"527","cid":"618","pattern":"adconnexa\\.com","name":"OxaMedia","id":"848"},
{"type":"tracker","aid":"528","cid":"552","pattern":"(cdn\\.(royale|statistics\\.live)|analytics)\\.spongecell\\.com\\/","name":"Spongecell","id":"850"},
{"type":"tracker","aid":"541","cid":"639","pattern":"((p(shared|files|thumbnails))|embed)\\.5min\\.com\\/","name":"5min Media","id":"864"},
{"type":"tracker","aid":"542","cid":"781","pattern":"stat\\.yellowtracker\\.com","name":"YellowTracker","id":"866"},
{"type":"tracker","aid":"543","cid":"780","pattern":"(adserver1(-images)?|bullseye)\\.backbeatmedia\\.com","name":"Back Beat Media","id":"867"},
{"type":"tracker","aid":"471","cid":"573","pattern":"ad\\.adserverplus\\.com","name":"Ybrant Media","id":"870"},
{"type":"tracker","aid":"546","cid":"283","pattern":"(amconf|core|adcontent)\\.videoegg\\.com\\/(siteconf|eap|alternates|ads)\\/","name":"Say Media","id":"871"},
{"type":"tracker","aid":"547","cid":"799","pattern":"contaxe\\.com\\/go","name":"Conteaxe","id":"873"},
{"type":"tracker","aid":"548","cid":"798","pattern":"ad\\.zanox\\.com","name":"Zanox","id":"874"},
{"type":"tracker","aid":"548","cid":"798","pattern":"zbox\\.zanox\\.com","name":"Zanox","id":"875"},
{"type":"tracker","aid":"548","cid":"798","pattern":"www\\.zanox-affiliate\\.de\\/ppv\\/","name":"Zanox","id":"876"},
{"type":"tracker","aid":"549","cid":"805","pattern":"rts\\.sparkstudios\\.com\\/","name":"Spark Studios","id":"878"},
{"type":"tracker","aid":"550","cid":"806","pattern":"adserver\\.juicyads\\.com","name":"JuicyAds","id":"879"},
{"type":"tracker","aid":"551","cid":"803","pattern":"ads\\.pheedo\\.com","name":"Pheedo","id":"880"},
{"type":"tracker","aid":"552","cid":"804","pattern":"www\\.cbox\\.ws\\/box","name":"Cbox","id":"881"},
{"type":"tracker","aid":"208","cid":"185","pattern":"yandex.ru\\/cycounter","name":"Yandex.Metrics","id":"882"},
{"type":"tracker","aid":"553","cid":"812","pattern":"ads\\.ad4game\\.com","name":"ad4game","id":"883"},
{"type":"tracker","aid":"554","cid":"811","pattern":"(a\\.ucoz\\.net|(do\\.am|at\\.ua)\\/stat\\/|ucoz\\.(.*)\\/(stat\\/|main/?a=ustat))","name":"uCoz","id":"884"},
{"type":"tracker","aid":"555","cid":"813","pattern":"c\\.bigmir\\.net","name":"bigmir","id":"885"},
{"type":"tracker","aid":"556","cid":"815","pattern":"\\.tradetracker\\.net","name":"TradeTracker","id":"886"},
{"type":"tracker","aid":"30","cid":"450","pattern":"gwp\\.nuggad\\.net","name":"Nugg.Ad","id":"887"},
{"type":"ad","aid":"557","cid":"500","pattern":"tqlkg\\.com\\/image","name":"Commission Junction","id":"888"},
{"type":"tracker","aid":"535","cid":"489","pattern":"ads\\.brand\\.net","name":"Brand.net","id":"890"},
{"type":"tracker","aid":"558","cid":"817","pattern":"js\\.geoads\\.com","name":"GeoAds","id":"891"},
{"type":"tracker","aid":"559","cid":"246","pattern":"certifica\\.js","name":"Certifica Metric","id":"892"},
{"type":"tracker","aid":"559","cid":"246","pattern":"certifica-js14\\.js","name":"Certifica Metric","id":"893"},
{"type":"tracker","aid":"559","cid":"246","pattern":"hits\\.e\\.cl","name":"Certifica Metric","id":"894"},
{"type":"tracker","aid":"559","cid":"246","pattern":"prima\\.certifica\\.com","name":"Certifica Metric","id":"895"},
{"type":"tracker","aid":"560","cid":"561","pattern":"ads\\.traffiq\\.com","name":"Traffiq","id":"896"},
{"type":"tracker","aid":"561","cid":"819","pattern":"livepass\\.conviva\\.com","name":"Conviva","id":"898"},
{"type":"tracker","aid":"538","cid":"700","pattern":"surveybuilder\\.buzzlogic\\.com","name":"BuzzLogic","id":"899"},
{"type":"ad","aid":"562","cid":"284","pattern":"cadreon\\.com\\/tags\\/defaultads","name":"Cadreon","id":"900"},
{"type":"tracker","aid":"566","cid":"820","pattern":"184\\.73\\.199\\.28\\/tracker\\/event","name":"SkyTide Anlaytics","id":"902"},
{"type":"tracker","aid":"567","cid":"823","pattern":"a\\.akncdn\\.com","name":"AdKeeper","id":"903"},
{"type":"tracker","aid":"568","cid":"242","pattern":"c\\.betrad\\.com\\/geo\\/ba\\.js","name":"Evidon Notice","id":"904"},
{"type":"tracker","aid":"569","cid":"289","pattern":"beacon\\.dedicatednetworks\\.com","name":"Dedicated Networks","id":"905"},
{"type":"ad","aid":"570","cid":"795","pattern":"ads\\.dedicatedmedia\\.com","name":"Dedicated Media","id":"906"},
{"type":"ad","aid":"540","cid":"632","pattern":"adserver\\.veruta\\.com","name":"Veruta","id":"908"},
{"type":"tracker","aid":"540","cid":"632","pattern":"veruta\\.com\\/scripts\\/trackmerchant\\.js","name":"Veruta","id":"909"},
{"type":"tracker","aid":"571","cid":"829","pattern":"anormal-tracker\\.de\\/tracker\\.js","name":"Anormal Tracker","id":"910"},
{"type":"tracker","aid":"571","cid":"829","pattern":"anormal-tracker\\.de\\/countv2\\.php","name":"Anormal Tracker","id":"911"},
{"type":"tracker","aid":"572","cid":"830","pattern":"roia\\.biz\\/","name":"TrackingSoft","id":"912"},
{"type":"tracker","aid":"573","cid":"432","pattern":"(ads|sync)\\.(adaptv|tidaltv)\\.(tv|com)","name":"Adap.tv","id":"913"},
{"type":"tracker","aid":"575","cid":"159","pattern":"specificmedia\\.com\\/otherassets\\/ad_options_icon\\.png","name":"Specific Media Notice","id":"915"},
{"type":"tracker","aid":"576","cid":"619","pattern":"\\.keewurd\\.com\\/","name":"Peerset","id":"916"},
{"type":"tracker","aid":"577","cid":"835","pattern":"rt\\.liftdna\\.com","name":"LiftDNA","id":"917"},
{"type":"tracker","aid":"578","cid":"834","pattern":"paid-to-promote\\.net\\/images\\/ptp\\.gif","name":"Paid-To-Promote","id":"918"},
{"type":"tracker","aid":"578","cid":"834","pattern":"777seo\\.com\\/","name":"Paid-To-Promote","id":"919"},
{"type":"tracker","aid":"361","cid":"428","pattern":"\\.bridgetrack\\.com\\/track","name":"BridgeTrack","id":"920"},
{"type":"ad","aid":"361","cid":"428","pattern":"\\.bridgetrack\\.com\\/a\\/s\\/","name":"BridgeTrack","id":"921"},
{"type":"tracker","aid":"49","cid":"181","pattern":"m\\.webtrends\\.com","name":"WebTrends","id":"922"},
{"type":"tracker","aid":"579","cid":"560","pattern":"\\.adsrvr\\.org","name":"TradeDesk","id":"923"},
{"type":"tracker","aid":"580","cid":"843","pattern":"hurra\\.com\\/ostracker\\.js","name":"Hurra Tracker","id":"925"},
{"type":"tracker","aid":"582","cid":"842","pattern":"sp1\\.convertro\\.com","name":"Convertro","id":"926"},
{"type":"tracker","aid":"526","cid":"532","pattern":"domdex\\.(net|com\\/f?c)","name":"Magnetic","id":"927"},
{"type":"tracker","aid":"526","cid":"532","pattern":"qjex\\.net","name":"Magnetic","id":"928"},
{"type":"tracker","aid":"504","cid":"684","pattern":"mi\\.adinterax\\.com\\/(js|customer)","name":"AdInterax","id":"929"},
{"type":"tracker","aid":"386","cid":"269","pattern":"cdn\\.undertone\\.com\\/js\\/ajs\\.js","name":"Undertone Networks","id":"930"},
{"type":"ad","aid":"583","cid":"434","pattern":"ad\\.adperium\\.com","name":"AdPerium","id":"931"},
{"type":"ad","aid":"583","cid":"434","pattern":"adlily\\.adperium\\.com","name":"AdPerium","id":"932"},
{"type":"ad","aid":"583","cid":"434","pattern":"\\.adperium\\.com\\/js\\/adframe.js","name":"AdPerium","id":"933"},
{"type":"tracker","aid":"583","cid":"434","pattern":"\\.adperium\\.com\\/abd\\.php","name":"AdPerium","id":"934"},
{"type":"tracker","aid":"13","cid":"81","pattern":"/__utm\\.","name":"Google Analytics","id":"935"},
{"type":"tracker","aid":"585","cid":"873","pattern":"tags\\.nabbr\\.com","name":"Nabbr","id":"936"},
{"type":"tracker","aid":"586","cid":"469","pattern":"\\.dmtry\\.com","name":"Adometry","id":"937"},
{"type":"tracker","aid":"91","cid":"295","pattern":"perf\\.overture\\.com","name":"Yahoo! Overture","id":"938"},
{"type":"tracker","aid":"587","cid":"222","pattern":"\\/ki\\.js\\/","name":"KissInsights","id":"939"},
{"type":"tracker","aid":"587","cid":"222","pattern":"j\\.kissinsights\\.com","name":"KissInsights","id":"940"},
{"type":"tracker","aid":"235","cid":"222","pattern":"doug1izaerwt3\\.cloudfront\\.net","name":"KissMetrics","id":"941"},
{"type":"tracker","aid":"20","cid":"50","pattern":"dnn506yrbagrg\\.cloudfront\\.net","name":"Crazy Egg","id":"942"},
{"type":"tracker","aid":"588","cid":"881","pattern":"cdn\\.optimizely\\.com\\/js\\/","name":"Optimizely","id":"943"},
{"type":"tracker","aid":"589","cid":"885","pattern":"webgozar\\.ir\\/c\\.aspx","name":"WebGozar","id":"944"},
{"type":"tracker","aid":"589","cid":"885","pattern":"webgozar\\.com\\/counter","name":"WebGozar","id":"945"},
{"type":"tracker","aid":"590","cid":"884","pattern":"r\\.i\\.ua","name":"i.ua","id":"946"},
{"type":"tracker","aid":"591","cid":"887","pattern":"hotlog\\.ru\\/cgi-bin\\/hotlog","name":"HotLog","id":"947"},
{"type":"ad","aid":"557","cid":"500","pattern":"qksz\\.net","name":"Commission Junction","id":"948"},
{"type":"ad","aid":"562","cid":"284","pattern":"d1qpxk1wfeh8v1\\.cloudfront\\.net","name":"Cadreon","id":"949"},
{"type":"tracker","aid":"592","cid":"890","pattern":"cn01\\.dwstat\\.cn","name":"dwstat.cn","id":"950"},
{"type":"ad","aid":"593","cid":"894","pattern":"(gopjn|pjatr|pjtra|pntra|pntrac|pntrs)\\.com\\/","name":"Pepperjam","id":"951"},
{"type":"ad","aid":"557","cid":"500","pattern":"ftjcfx\\.com","name":"Commission Junction","id":"952"},
{"type":"ad","aid":"557","cid":"500","pattern":"tqlkg\\.com","name":"Commission Junction","id":"953"},
{"type":"ad","aid":"557","cid":"500","pattern":"yceml\\.net","name":"Commission Junction","id":"954"},
{"type":"tracker","aid":"594","cid":"891","pattern":"analytics\\.matchbin\\.com","name":"Matchbin","id":"955"},
{"type":"ad","aid":"594","cid":"891","pattern":"ads\\.matchbin\\.com","name":"Matchbin","id":"956"},
{"type":"ad","aid":"595","cid":"892","pattern":"shareasale\\.com","name":"ShareASale","id":"957"},
{"type":"ad","aid":"596","cid":"893","pattern":"pages\\.etology\\.com\\/","name":"Etology","id":"958"},
{"type":"tracker","aid":"508","cid":"761","pattern":"s\\.thebrighttag\\.com","name":"BrightTag","id":"959"},
{"type":"ad","aid":"597","cid":"878","pattern":"ads2?\\.smowtion\\.com","name":"Smowtion","id":"960"},
{"type":"tracker","aid":"598","cid":"837","pattern":"imgsrv\\.nextag\\.com\\/imagefiles\\/includes\\/roitrack\\.js","name":"Nextag ROI Optimizer","id":"961"},
{"type":"ad","aid":"33","cid":"14","pattern":"rcm-ca\\.amazon\\.ca\\/e\\/cm","name":"Amazon Associates","id":"962"},
{"type":"ad","aid":"33","cid":"14","pattern":"rcm-uk\\.amazon\\.co\\.uk\\/e\\/cm","name":"Amazon Associates","id":"963"},
{"type":"ad","aid":"33","cid":"14","pattern":"rcm-de\\.amazon\\.de\\/e\\/cm","name":"Amazon Associates","id":"964"},
{"type":"ad","aid":"310","cid":"257","pattern":"fls\\.doubleclick\\.net","name":"DoubleClick Floodlight","id":"965"},
{"type":"tracker","aid":"599","cid":"474","pattern":"pixel\\.adsafeprotected\\.com","name":"AdSafe","id":"966"},
{"type":"tracker","aid":"599","cid":"474","pattern":"fw\\.adsafeprotected\\.com","name":"AdSafe","id":"967"},
{"type":"ad","aid":"533","cid":"668","pattern":"\\.tradedoubler\\.com","name":"TradeDoubler","id":"968"},
{"type":"ad","aid":"600","cid":"904","pattern":"\\.streamray\\.com","name":"FriendFinder Network","id":"969"},
{"type":"ad","aid":"600","cid":"904","pattern":"\\.pop6\\.com","name":"FriendFinder Network","id":"970"},
{"type":"ad","aid":"600","cid":"904","pattern":"\\.cams\\.com","name":"FriendFinder Network","id":"971"},
{"type":"ad","aid":"600","cid":"904","pattern":"\\.nostringsattached\\.com","name":"FriendFinder Network","id":"972"},
{"type":"ad","aid":"600","cid":"904","pattern":"\\.getiton\\.com","name":"FriendFinder Network","id":"973"},
{"type":"ad","aid":"600","cid":"904","pattern":"\\.adultfriendfinder\\.com","name":"FriendFinder Network","id":"974"},
{"type":"ad","aid":"600","cid":"904","pattern":"\\.double-check\\.com","name":"FriendFinder Network","id":"975"},
{"type":"ad","aid":"600","cid":"904","pattern":"\\.facebookofsex\\.com","name":"FriendFinder Network","id":"976"},
{"type":"tracker","aid":"85","cid":"311","pattern":"mediacdn\\.disqus\\.com","name":"Disqus","id":"977"},
{"type":"tracker","aid":"100","cid":"55","pattern":"widgets\\.digg\\.com","name":"Digg Widget","id":"978"},
{"type":"ad","aid":"18","cid":"99","pattern":"\\.lijit\\.com\\/delivery","name":"Lijit","id":"979"},
{"type":"ad","aid":"601","cid":"310","pattern":"cdn\\.technoratimedia\\.com","name":"Technorati Media","id":"980"},
{"type":"tracker","aid":"36","cid":"70","pattern":"log\\.feedjit\\.com","name":"Feedjit","id":"981"},
{"type":"ad","aid":"502","cid":"631","pattern":"\\.smartadserver\\.com","name":"SMART AdServer","id":"982"},
{"type":"ad","aid":"602","cid":"886","pattern":"\\.sponsorads\\.de","name":"SponsorAds.de","id":"983"},
{"type":"ad","aid":"37","cid":"80","pattern":"google\\.com\\/afsonline\\/show_afs_ads\\.js","name":"Google Adsense","id":"984"},
{"type":"ad","aid":"473","cid":"738","pattern":"conduit-banners\\.com","name":"Conduit","id":"985"},
{"type":"tracker","aid":"503","cid":"635","pattern":"spotxchange\\.com\\/track","name":"SpotXchange","id":"986"},
{"type":"ad","aid":"603","cid":"924","pattern":"adserver\\.advertisespace\\.com","name":"AdvertiseSpace","id":"987"},
{"type":"ad","aid":"603","cid":"924","pattern":"ads\\.advertisespace\\.com","name":"AdvertiseSpace","id":"988"}];

console.log(bugs);
/*
var partial_patterns_arr = [];

for (var i = 0; i < bugs.length; i++) {
        var bug = bugs[i]; //this.bugs[i];
        bug.regex = new RegExp(bug.pattern);
        
        var pattern = bug.pattern;

        if (bug.pattern.match(/^[A-z0-9;\-_(\\\.)(\\\/)]+$/)) {
                bug.str = bug.pattern.replace(/\\([\.\/])/g, '$1');
        } else {
                 //console.log(pattern.toString());
                partial_patterns_arr.push(pattern);
        }
}

console.log(partial_patterns_arr.join('|'));

var partialRegex;
if (partial_patterns_arr.length > 0) {
    try {
        partialRegex = new RegExp(partial_patterns_arr.join('|'), 'i');
    } catch (e) {
        console.log('Pattern breaks here: ' + partial_patterns_arr.join('|'));
    }
}
*/
